import React, { useState, useEffect, useCallback } from 'react';
import { Accordion, Checkbox, RingProgress, Text, Button, TextInput, ActionIcon, Group, Stack, Badge, Loader, Paper, Center } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { Package, Plus, Trash2, Sparkles, FileText, Shirt, Laptop, Pill, Glasses, ShoppingBag } from 'lucide-react';

const CATEGORY_CONFIG = {
  'Documents': { icon: FileText, color: 'blue', bg: 'bg-blue-50', border: 'border-blue-100', text: 'text-blue-600' },
  'Clothing': { icon: Shirt, color: 'violet', bg: 'bg-violet-50', border: 'border-violet-100', text: 'text-violet-600' },
  'Electronics': { icon: Laptop, color: 'cyan', bg: 'bg-cyan-50', border: 'border-cyan-100', text: 'text-cyan-600' },
  'Toiletries': { icon: ShoppingBag, color: 'pink', bg: 'bg-pink-50', border: 'border-pink-100', text: 'text-pink-600' },
  'Medicine': { icon: Pill, color: 'red', bg: 'bg-red-50', border: 'border-red-100', text: 'text-red-600' },
  'Accessories': { icon: Glasses, color: 'orange', bg: 'bg-orange-50', border: 'border-orange-100', text: 'text-orange-600' },
};

const getConfig = (category) => CATEGORY_CONFIG[category] || { icon: Package, color: 'gray', bg: 'bg-slate-50', border: 'border-slate-100', text: 'text-slate-600' };

export default function PackingAssistant({ tripId }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [newItemInputs, setNewItemInputs] = useState({});

  const fetchItems = useCallback(async () => {
    try {
      const res = await fetch(`/api/packing/${tripId}`);
      if (res.ok) {
        const data = await res.json();
        setItems(data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [tripId]);

  useEffect(() => {
    fetchItems();
  }, [fetchItems]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await fetch(`/api/packing/generate/${tripId}`, { method: 'POST' });
      const data = await res.json();
      if (data.items) {
        setItems(data.items);
        notifications.show({
          title: 'Checklist Ready!',
          message: `${data.count} items generated by AI.`,
          color: 'green'
        });
      }
    } catch (e) {
      notifications.show({
        title: 'Error',
        message: 'Failed to generate packing list.',
        color: 'red'
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleToggle = async (itemId, currentState) => {
    const nextState = currentState ? 0 : 1;
    // Optimistic UI update
    setItems(prev => prev.map(i => i.id === itemId ? { ...i, is_checked: nextState } : i));
    try {
      const res = await fetch(`/api/packing/item/${itemId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ is_checked: nextState })
      });
      if (!res.ok) {
        // Rollback
        setItems(prev => prev.map(i => i.id === itemId ? { ...i, is_checked: currentState } : i));
      }
    } catch (e) {
      setItems(prev => prev.map(i => i.id === itemId ? { ...i, is_checked: currentState } : i));
    }
  };

  const handleDelete = async (itemId) => {
    setItems(prev => prev.filter(i => i.id !== itemId));
    try {
      await fetch(`/api/packing/item/${itemId}`, { method: 'DELETE' });
    } catch (e) {
      fetchItems();
    }
  };

  const handleAddItem = async (category) => {
    const name = (newItemInputs[category] || '').trim();
    if (!name) return;
    try {
      const res = await fetch(`/api/packing/${tripId}/item`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ category, item_name: name })
      });
      if (res.ok) {
        const item = await res.json();
        setItems(prev => [...prev, item]);
        setNewItemInputs(prev => ({ ...prev, [category]: '' }));
      }
    } catch (e) {
      console.error(e);
    }
  };

  if (loading) {
    return (
      <Center py="xl">
        <Loader size="sm" color="blue" />
      </Center>
    );
  }

  const totalItems = items.length;
  const checkedItems = items.filter(i => i.is_checked === 1).length;
  const progress = totalItems > 0 ? Math.round((checkedItems / totalItems) * 100) : 0;

  // Group by category
  const grouped = {};
  items.forEach(item => {
    if (!grouped[item.category]) grouped[item.category] = [];
    grouped[item.category].push(item);
  });

  if (totalItems === 0) {
    return (
      <Paper p="xl" radius="xl" withBorder className="bg-white border-slate-200 shadow-sm text-center">
        <Stack align="center" gap="md" py="lg">
          <div className="w-12 h-12 rounded-full bg-blue-50 border border-blue-100 flex items-center justify-center">
            <Package className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <Text fw={700} size="sm" c="dark">Packing Assistant</Text>
            <Text size="xs" c="dimmed" mt={4}>Generate an AI checklist based on your destination, weather, and bookings.</Text>
          </div>
          <Button
            size="xs"
            radius="md"
            color="blue"
            leftSection={generating ? <Loader size={12} color="white" /> : <Sparkles className="w-3.5 h-3.5" />}
            onClick={handleGenerate}
            disabled={generating}
            className="font-semibold shadow-sm mt-2"
          >
            {generating ? 'Generating...' : 'Generate AI Checklist'}
          </Button>
        </Stack>
      </Paper>
    );
  }

  return (
    <Stack gap="md" className="w-full">
      {/* Progress Header */}
      <Paper p="md" radius="xl" withBorder className="bg-white border-slate-200 shadow-sm">
        <Group justify="space-between" align="center">
          <Group gap="md">
            <RingProgress
              size={56}
              thickness={5}
              roundCaps
              sections={[{ value: progress, color: progress === 100 ? 'teal' : 'blue' }]}
              label={
                <Center>
                  <Text size="10px" fw={800} c={progress === 100 ? 'teal' : 'blue'}>{progress}%</Text>
                </Center>
              }
            />
            <div>
              <Text fw={750} size="sm" c="dark">Packing Progress</Text>
              <Text size="xs" c="dimmed">
                {checkedItems} / {totalItems} items packed
                {progress === 100 && ' — Ready to fly! ✈️'}
              </Text>
            </div>
          </Group>
          <Button
            variant="light"
            size="xs"
            radius="md"
            color="blue"
            leftSection={generating ? <Loader size={12} /> : <Sparkles className="w-3 h-3" />}
            onClick={handleGenerate}
            disabled={generating}
          >
            Regenerate
          </Button>
        </Group>
      </Paper>

      {/* Category Accordions */}
      <Accordion variant="separated" radius="lg" chevronPosition="right" defaultValue={Object.keys(grouped)} multiple>
        {Object.entries(grouped).map(([category, categoryItems]) => {
          const config = getConfig(category);
          const Icon = config.icon;
          const catChecked = categoryItems.filter(i => i.is_checked === 1).length;

          return (
            <Accordion.Item key={category} value={category} className="bg-white border border-slate-200/80 shadow-sm">
              <Accordion.Control>
                <Group gap="sm">
                  <div className={`w-8 h-8 rounded-lg ${config.bg} ${config.border} border flex items-center justify-center`}>
                    <Icon className={`w-4 h-4 ${config.text}`} />
                  </div>
                  <div className="flex-1">
                    <Text fw={700} size="xs" className="text-slate-800 uppercase tracking-wider">{category}</Text>
                  </div>
                  <Badge size="xs" variant="light" color={catChecked === categoryItems.length ? 'teal' : config.color} radius="md">
                    {catChecked}/{categoryItems.length}
                  </Badge>
                </Group>
              </Accordion.Control>
              <Accordion.Panel>
                <Stack gap="xs" mt="xs">
                  {categoryItems.map(item => (
                    <Group key={item.id} justify="space-between" align="center" className="py-1 px-2 rounded-lg hover:bg-slate-50/80 transition-colors">
                      <Checkbox
                        checked={item.is_checked === 1}
                        onChange={() => handleToggle(item.id, item.is_checked === 1)}
                        label={
                          <Text size="xs" td={item.is_checked === 1 ? 'line-through' : undefined} c={item.is_checked === 1 ? 'dimmed' : 'slate.800'} fw={500}>
                            {item.item_name}
                          </Text>
                        }
                        color="blue"
                        radius="xs"
                      />
                      <Group gap={6}>
                        {item.created_by === 'user' && (
                          <Badge size="9px" variant="dot" color="grape">User</Badge>
                        )}
                        <ActionIcon
                          variant="subtle"
                          color="red"
                          size="sm"
                          onClick={() => handleDelete(item.id)}
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </ActionIcon>
                      </Group>
                    </Group>
                  ))}
                  
                  {/* Add Custom Item */}
                  <Group gap="xs" mt="sm" pt="sm" className="border-t border-slate-100">
                    <TextInput
                      placeholder={`Add custom item to ${category}...`}
                      size="xs"
                      radius="md"
                      className="flex-1"
                      value={newItemInputs[category] || ''}
                      onChange={(e) => setNewItemInputs(prev => ({ ...prev, [category]: e.target.value }))}
                      onKeyDown={(e) => e.key === 'Enter' && handleAddItem(category)}
                    />
                    <ActionIcon
                      variant="light"
                      color="blue"
                      size="md"
                      radius="md"
                      onClick={() => handleAddItem(category)}
                    >
                      <Plus className="w-4 h-4" />
                    </ActionIcon>
                  </Group>
                </Stack>
              </Accordion.Panel>
            </Accordion.Item>
          );
        })}
      </Accordion>
    </Stack>
  );
}
